[package]
name = "rustcoin"
version = "0.1.0"
authors = ["SkyBeastMC <skybeastmc@gmail.com>"]
edition = "2018"

[dependencies]
secp256k1 = "0.5.6"
hex-literal = "0.1.1"
hex = "0.3.2"
generic-array = "0.12.0"
digest = "0.8.0"
sha2 = "0.8.0"
ripemd160 = "0.8.0"
base58 = "0.1.0"
